#!/bin/bash
#===============================================================================
# easy-kvm : 新しい仮想マシンを作成する
# Date     : 2015/4/19 Start
# Copyright: Original code by Yusuke Komori.
#                       Copyright (c) 2015. Yusuke Komori, All rights reserved.
#===============================================================================

# TODO
#  o ミラーサイトを選択できるようにする
#  o 取得パスの外部化

SCRIPT_BASE=`echo $(cd $(dirname $0); pwd)`
SCRIPT_NAME=`basename $0`

# defaults
NUM_CPU=2
MEM_SIZE=1536
DISK_SIZE=30
SWAP_SIZE=2048
GATEWAY=192.168.122.1
NAME_SERVER=192.168.122.1

BOOT_PARTITION_SIZE=300

OS_LIST=${SCRIPT_BASE}/template/os-list

MIRROR_BASE=http://ftp.iij.ad.jp/pub/linux/centos
#MIRROR_BASE=http://ftp.jaist.ac.jp/pub/Linux/CentOS
#MIRROR_BASE=http://www.ftp.ne.jp/Linux/packages/CentOS
#MIRROR_BASE=http://ftp.riken.jp/Linux/centos

OS_LOCATION_CENTOS5=${MIRROR_BASE}/5.11/os/x86_64/
OS_LOCATION_CENTOS6=${MIRROR_BASE}/6.8/os/x86_64/
OS_LOCATION_CENTOS7=${MIRROR_BASE}/7/os/x86_64/

ISO_LOCATION_CENTOS72=${MIRROR_BASE}/7.2.1511/isos/x86_64/CentOS-7-x86_64-DVD-1511.iso 
OS_LOCATION_CENTOS72=${MIRROR_BASE}/7.2.1511/os/x86_64/

ISO_LOCATION_CENTOS73=${MIRROR_BASE}/7.3.1611/isos/x86_64/CentOS-7-x86_64-DVD-1611.iso
OS_LOCATION_CENTOS73=${MIRROR_BASE}/7.3.1611/os/x86_64/

VOL_BASE=/var/lib/libvirt/images
POOL=default

TPL_KS_DIR="${SCRIPT_BASE}/template/kickstart"
TPL_PS_DIR="${SCRIPT_BASE}/template/post-script"

QEMU_HOOK=/etc/libvirt/hooks/qemu

#-------------------------------------------------------------------------------
#- common functions ------------------------------------------------------------

__setupcolor() { #{{{
  # Escape sequence
  ESC="\e["
  ESCEND=m
  C_OFF=${ESC}${ESCEND}

  # normal
  C_BLACK="${ESC}30${ESCEND}"
  C_RED="${ESC}31${ESCEND}"
  C_GREEN="${ESC}32${ESCEND}"
  C_YELLOW="${ESC}33${ESCEND}"
  C_BLUE="${ESC}34${ESCEND}"
  C_MAGENTA="${ESC}35${ESCEND}"
  C_CYAN="${ESC}36${ESCEND}"
  C_WHITE="${ESC}37${ESCEND}"

  RES_COL=60
  MOVE_TO_COL="echo -en \\033[${RES_COL}G"
}
#}}}

__show_ok() { #{{{
  [ "${SILENT_MODE}" ] && return
  [[ "$1" && "$1" -gt 0 ]] && echo -en "\\033[${1}G"
  echo -en "[ ${C_GREEN}OK${C_OFF}"
  [ "$2" ] && echo " ]$2" || echo " ]"
}
#}}}

__show_info() { #{{{
  [[ -n "${SILENT_MODE}" ]] && return
  [[ "$1" == "-n" ]] && echo -en "${C_CYAN}${2}${C_OFF}" || echo -e "${C_CYAN}${1}${C_OFF}"
}
#}}}

__show_error() { #{{{
  echo -e "[${C_RED}ERROR${C_OFF}] $1"
}
#}}}

__error_end() { #{{{
  __show_error "$1"; exit 1
}
#}}}

__confirm() { #{{{
  [[ "$1" != "" ]] && echo -en "$1" || echo -n "OK?"
  echo -n " (y/n) "

  while :; do
    read -s -n 1 CHAR
    case $CHAR in
      y|Y) RESULT=0; break ;;
      n|N) RESULT=1; break ;;
      *)   ;;
    esac
  done

  echo $CHAR
  return $RESULT
}
#}}}

#-------------------------------------------------------------------------------
#- functions -------------------------------------------------------------------

# usage
_usage() { #{{{
  [ "$1" ] && __show_error "$1"
  echo "usege : "
  echo "  setup で Kickstart 用 config ファイルを作成し、"
  echo "  create で config ファイルを元に仮想マシンを作成します。"
  echo ""
  echo "  $SCRIPT_NAME setup KS_CFG_PATH -w -h HOST_NAME -o OS [-c VCPUS] "
  echo "                     [-m MEMORY_SIZE] [-d DISK_SIZE] [-f STORAGE_FORMAT] "
  echo "                     -i IP_ADDR/NET_MASK [-g GATEWAY] [-n NAME_SERVER] "
  echo "                     [-p ISO_PATH]"
  echo "    KS_CFG_PATH にKickstart用設定ファイルを出力します."
  echo ""
  echo "  $SCRIPT_NAME create KS_CFG_PATH [-w] [-O ISO_PATH]"
  echo "    KS_CFG_PATH で指定したパスの Kickstart 用設定ファイル"
  echo "    を元に仮想マシンを構成します."
  echo "          -w : Why run (show only virt-install command line)"
  echo "          -h : host(kvm domain) name"
  echo "          -o : OS:VERSION (ex. centos:7.3)"
  echo "          -c : number of virtual cpus (default:$NUM_CPU)"
  echo "          -m : memory size (MBytes) (defaullt:$MEM_SIZE Mbytes)"
  echo "          -d : disk size (GBytes) (default:$DISK_SIZE Gbytes)"
  echo "          -f : storage format (raw / raw:s / qcow2 /qcow2:s) (default:raw:s)"
  echo "                 ':s' represents using sparse file."
  echo "          -i : ip address and net mask (ex. 192.168.122.2/24)"
  echo "          -g : Gateway's ip address (default: $GATEWAY)"
  echo "          -n : Name server's ip address (default: $NAME_SERVER)"
  echo "          -p : OS's iso image path"
  echo "          -O : Offline install 引数が指定されていればそのパスのISOを読み込み、そうでなければ ks ファイル中の ISO ファイルを読み込む"
  echo ""
  echo "  $SCRIPT_NAME install-qemu-forward"
  echo "    qemu-forward スクリプトをインストールします."
  exit 1
}
#}}}

# check if libvirtd is installed
_check_libvirtd() { #{{{
  local ERR=
  which virsh > /dev/null 2>&1 || ERR=yes
  which virt-install > /dev/null 2>&1 || ERR=yes
  if [[ $ERR ]]; then
    __error_end "Virtualization group is not installed. \
Please execute following command as the root user.\n\
  LANG=C yum groupinstall Virtualization 'Virtualization Client' 'Virtualization Platform' 'Virtualization Tools'"
  fi
}
#}}}


# init storage format
_init_storage_format() { #{{{
  local STORAGE_FORMAT_ORG="$1"
  [[ ! $STORAGE_FORMAT_ORG ]] && STORAGE_FORMAT_ORG=raw:s  # default storage format

  case "$STORAGE_FORMAT_ORG" in
    qcow2|qcow2:s) STORAGE_FORMAT=qcow2; VOL_EXT=qcow2 ;;
    raw|raw:s) STORAGE_FORMAT=raw; VOL_EXT=img ;;
    *) __error_end "Invalid storage format. : $STORAGE_FORMAT_ORG" ;;
  esac

  case "$STORAGE_FORMAT_ORG" in
    qcow2:s|raw:s) SPARSE=yes ;;
    *) SPARSE=no ;;
  esac
}
#}}}

################################################################################
# setup mode
################################################################################
_setup() { #{{{
  # check arguments
  # hostname
  [[ ! "${HOST_NAME}" ]] && _usage "hostname is not specified."

  # os
  [[ ! "${OS}" ]] && _usage "os is not specified."
  local OS_NAME=`echo "$OS" | sed -re 's|([^:]+):.+|\1|'`
  local OS_VERSION=`echo "$OS" | sed -re 's|[^:]+:(.*)|\1|'`
  local OS_MAJOR_VERSION=`echo "$OS" | sed -re 's|.+:([0-9]+).*|\1|'`
  [[ ! -f "${OS_LIST}" ]] && __error_end "os list files is not found. : ${OS_LIST}"
  OS_DEF=`cat ${OS_LIST} | grep -Ev '^[ \t]*#' | grep -E "^[ \t]*${OS}[ ^t]+.+" | tail -n 1`
  [[ ! "${OS_DEF}" ]] && __error_end "unsupported os : ${OS}\n  see ${OS_LIST}"
  read OS OS_VALIANT OS_LOCATION < <(echo "${OS_DEF}")

  # network config
  [[ ! "$IP" ]] && _usage "ip address is not specified."
  IP_ADDR=`echo $IP | sed -re 's|(.+)/(.+)|\1|'`
  NET_MASK=`echo $IP | sed -re 's|(.+)/(.+)|\2|'`
  [[ "$IP_ADDR" == "$NET_MASK" ]] && NET_MASK=
  case "$NET_MASK" in
    32) NET_MASK=255.255.255.255 ;;
    24) NET_MASK=255.255.255.0 ;;
    16) NET_MASK=255.255.0.0 ;;
    8) NET_MASK=255.0.0.0 ;;
    *) NET_MASK=255.255.255.0 ;; # default
  esac

  # disk
  DISK_SIZE_MB=`expr "${DISK_SIZE}" '*' 1024`

  # check iso file
  [[ "$ISO_PATH" ]] && [[ ! -f "$ISO_PATH" ]] && __error_end "Iso file is not found. : $ISO_PATH"

  # temlate
  KS_TEMPLATE="${TPL_KS_DIR}/${OS_NAME}:${OS_MAJOR_VERSION}.tpl"
  [[ ! -f "$KS_TEMPLATE" ]] && __error_end "Kick-start template file is not found. : $KS_TEMPLATE"
  POST_SCRIPT_TEMPLATE="${TPL_PS_DIR}/post-script_${OS_NAME}:${OS_MAJOR_VERSION}.tpl"
  [[ ! -f "$POST_SCRIPT_TEMPLATE" ]] && __error_end "Post-script template file is not found. : $POST_SCRIPT_TEMPLATE"


  echo -e "${C_CYAN}$SCRIPT_NAME : $CMD${C_OFF}"

  echo -e "${C_CYAN}Hostname       ${C_OFF}: $HOST_NAME"
  echo -e "${C_CYAN}OS             ${C_OFF}: $OS"
  echo -e "${C_CYAN}OS location    ${C_OFF}: $OS_LOCATION"
  echo -e "${C_CYAN}ISO path       ${C_OFF}: $ISO_PATH"
  echo -e "${C_CYAN}VCPUs          ${C_OFF}: $NUM_CPU"
  echo -e "${C_CYAN}Ram(MB)        ${C_OFF}: $MEM_SIZE"
  echo -e "${C_CYAN}Disk(GB)       ${C_OFF}: $DISK_SIZE (${DISK_SIZE_MB} Mbytes)"
  echo -e "${C_CYAN}Swap(MB)       ${C_OFF}: $SWAP_SIZE"
  echo -e "${C_CYAN}Storage format ${C_OFF}: $STORAGE_FORMAT (sparse=${SPARSE})"
  echo -e "${C_CYAN}IP address     ${C_OFF}: $IP_ADDR"
  echo -e "${C_CYAN}netmask        ${C_OFF}: $NET_MASK"
  echo -e "${C_CYAN}Gateway        ${C_OFF}: $GATEWAY"
  echo -e "${C_CYAN}Name server    ${C_OFF}: $NAME_SERVER"
  echo ''

  __confirm "Are you sure ?" || exit

  # create Kickstart config
  # Check kickstart path
  [[ ! -d "`dirname ${KS_PATH}`" ]] && __error_end "Directory not found. : `dirname ${KS_PATH}`"
  if [[ -f "$KS_PATH" ]]; then
    __confirm "$KS_PATH is already exists. Create it anyway?" || exit
    rm -f "$KS_PATH"
  fi

  echo -e "${C_GREEN}Creating kick start configuration... ${C_OFF}"
  TMPFILE=`mktemp -p /dev/shm`
  echo "# param HOST_NAME=$HOST_NAME" >> "$KS_PATH"
  echo "# param NUM_CPU=$NUM_CPU" >> "$KS_PATH"
  echo "# param MEM_SIZE=$MEM_SIZE" >> "$KS_PATH"
  echo "# param DISK_SIZE=$DISK_SIZE" >> "$KS_PATH"
  echo "# param STORAGE_FORMAT=$STORAGE_FORMAT_ORG" >> "$KS_PATH"
  echo "# param OS_VALIANT=$OS_VALIANT" >> "$KS_PATH"
  echo "# param OS_LOCATION=$OS_LOCATION" >> "$KS_PATH"
  echo "# param ISO_PATH=$ISO_PATH" >> "$KS_PATH"

  cat $KS_TEMPLATE $POST_SCRIPT_TEMPLATE | sed -re "s/%\{HOST_NAME\}/${HOST_NAME}/g" \
    -e "s/%\{IP_ADDR\}/${IP_ADDR}/g" \
    -e "s/%\{NET_MASK\}/${NET_MASK}/g" \
    -e "s/%\{GATEWAY\}/${GATEWAY}/g" \
    -e "s/%\{NS\}/${NAME_SERVER}/g" \
    -e "s/%\{BOOT_PARTITION_SIZE\}/${BOOT_PARTITION_SIZE}/g" \
    -e "s/%\{DISK_SIZE\}/${DISK_SIZE_MB}/g" \
    -e "s/%\{SWAP_SIZE\}/${SWAP_SIZE}/g" \
    -e "s|%\{OS_LOCATION\}|${OS_LOCATION}|g" \
    -e "s|%\{ISO_PATH\}|${ISO_PATH}|g" \
    > $TMPFILE

  if [ "${ISO_PATH}" ]; then
    # install from iso file
    sed -i -re 's/#cdrom/cdrom/' $TMPFILE
  else
    # install from network
    sed -i -re 's/#url/url/' $TMPFILE
  fi

  cat "$TMPFILE" >> "$KS_PATH"
  echo -e "${C_CYAN}Kick start configuration was created as${C_OFF} $KS_PATH"
  rm $TMPFILE

  exit 0
}
#}}}

################################################################################
# create mode
################################################################################
_create() { #{{{
  _check_libvirtd

  [[ ! $UID -eq 0 ]] && __error_end 'Please perform this operation as the root user.'

  # check KS_CFG_PATH
  KS_WORK_FILE=`mktemp -p /dev/shm`
  echo -en "${C_GREEN}Checking kick start file... ${C_OFF} : $KS_CFG_PATH"
  [[ ! -f "$KS_CFG_PATH" ]] && ( echo ''; __error_end "Kick start file is not exists. : $KS_CFG_PATH"; )
  cp "$KS_CFG_PATH" "$KS_WORK_FILE"
  echo -e " [ ${C_GREEN}OK${C_OFF} ]"
  echo ''

  # load paramters
  echo -en "${C_GREEN}Loading parameters... ${C_OFF}"
  eval `cat "$KS_WORK_FILE" | egrep "^# param" | sed -re 's/^# param //'`
  echo -e " [ ${C_GREEN}OK${C_OFF} ]"

  [[ -f "$KS_WORK_FILE" ]] && rm "$KS_WORK_FILE"

  KS_DIR=`mktemp -d -p /dev/shm`
  cp ${KS_CFG_PATH} ${KS_DIR}/
  KS_WORK_FILE=${KS_DIR}/`basename ${KS_CFG_PATH}`

  STORAGE_FORMAT_ORG="$STORAGE_FORMAT"; unset STORAGE_FORMAT
  _init_storage_format "$STORAGE_FORMAT_ORG"

  # get network information
  IP_ADDR=`cat "$KS_WORK_FILE" | grep '^network ' | sed -re 's/.+ --ip=([0-9\.]+).*/\1/'`
  [[ ! ${IP_ADDR} ]] && __error_end "can't retrieve ip address from ${KS_WORK_FILE}"
  GATEWAY=`cat "$KS_WORK_FILE" | grep '^network ' | sed -re 's/.+ --gateway=([0-9\.]+).*/\1/'`
  NAME_SERVER=`cat "$KS_WORK_FILE" | grep '^network ' | sed -re 's/.+ --nameserver=([0-9\.]+).*/\1/'`
  NET_MASK=`cat "$KS_WORK_FILE" | grep '^network ' | sed -re 's/.+ --netmask=([0-9\.]+).*/\1/'`

  # check iso file (for offline installation)
  local PATH_OK=
  if [ "${OFFLINE}" ]; then
    # Install from local iso file
    if [[ "${CMD_ISO_PATH}" ]]; then
      [[ -f "${CMD_ISO_PATH}" ]] || __error_end "File not found. : ${CMD_ISO_PATH}"
      ISO_PATH=${CMD_ISO_PATH}
      PATH_OK=yes
    else
      [[ ! "${ISO_PATH}" ]] && __error_end "ISO_PATH is not specified."
      [[ -f "${ISO_PATH}" ]] || __error_end "File not found. : ${ISO_PATH}"
      PATH_OK=yes
    fi
    [[ ! "${PATH_OK}" = 'yes' ]] && __error_end "ISO_PATH is not specified."

    sudo -u qemu test -r "${ISO_PATH}"
    [[ ! $? -eq 0 ]] && __error_end "qemu user can't access iso file. : ${ISO_PATH}"
    INSTALL_FROM="--location=${ISO_PATH}"

    sed -i -re 's/^[# \t]*cdrom$/cdrom/' ${KS_WORK_FILE}
    sed -i -re 's/^[ \t]*(url[ \t]+.+)$/#\1/' ${KS_WORK_FILE}
  else
    # Install from internet
    [[ ! "${OS_LOCATION}" ]] && __error_end "OS_LOCATION is not specified."
    INSTALL_FROM="--location=${OS_LOCATION}"
    sed -i -re 's/^[ \t]*cdrom$/#cdrom/' ${KS_WORK_FILE}
    sed -i -re "s|^[# \\t]*url[ \\t]+.+$|url --url ${OS_LOCATION}|" ${KS_WORK_FILE}
  fi

  # check volume
  VOL_NAME=${HOST_NAME}
  VOL_PATH=${VOL_BASE}/${VOL_NAME}.${VOL_EXT}
  virsh vol-list --pool=$POOL | grep "$VOL_NAME"
  [[ $? -eq 0 ]] && __error_end "Volume is already exists. : $VOL_PATH ($POOL/$VOL_NAME)"
  [[ -f "$VOL_PATH" ]] && __error_end "Volume image file is already exists. : $VOL_PATH ($POOL/$VOL_NAME)"
  VOL_NAME=${POOL}/${HOST_NAME}

  # confirm
  echo -e "${C_CYAN}$SCRIPT_NAME : $CMD${C_OFF}"
  echo -e "${C_CYAN}Hostname       ${C_OFF}: $HOST_NAME"
  echo -e "${C_CYAN}OS Valiant     ${C_OFF}: $OS_VALIANT"
  if [ ! "$OFFLINE" ]; then
    echo -e "${C_CYAN}OS location    ${C_OFF}: $OS_LOCATION"
  else
    echo -e "${C_CYAN}ISO file path  ${C_OFF}: $ISO_PATH"
  fi
  echo -e "${C_CYAN}VCPUs          ${C_OFF}: $NUM_CPU"
  echo -e "${C_CYAN}Ram(MB)        ${C_OFF}: $MEM_SIZE"
  echo -e "${C_CYAN}Disk(GB)       ${C_OFF}: $DISK_SIZE"
  echo -e "${C_CYAN}Pool           ${C_OFF}: $POOL"
  echo -e "${C_CYAN}Volume name    ${C_OFF}: $VOL_NAME"
  echo -e "${C_CYAN}Volume path    ${C_OFF}: $VOL_PATH"
  echo -e "${C_CYAN}Storage format ${C_OFF}: $STORAGE_FORMAT (sparse=${SPARSE})"
  echo -e "${C_CYAN}IP Address     ${C_OFF}: $IP_ADDR"
  echo -e "${C_CYAN}Net mask       ${C_OFF}: $NET_MASK"
  echo -e "${C_CYAN}Gateway        ${C_OFF}: $GATEWAY"
  echo -e "${C_CYAN}Name server    ${C_OFF}: $NAME_SERVER"
  echo -ne "${C_CYAN}Install from   ${C_OFF}: "
  if [[ "${OFFLINE}" ]]; then
    echo "${ISO_PATH}"
  else
    echo "${INSTALL_FROM}" | sed -re "s/(--location=|--cdrom=)//"
  fi
  
  echo ''

  if [ ! "$WHY_RUN" ]; then
    __confirm "Are you sure ?" || exit
  fi

  # Create VM
  INITRD_PARAM="--initrd-inject=${KS_WORK_FILE}"
  KS_URL=file:/`basename "${KS_WORK_FILE}"`

  # create virt-install options
  VIRT_OPT=()
  VIRT_OPT+=(--connect qemu:///system)
  VIRT_OPT+=(--name "${HOST_NAME}")
  VIRT_OPT+=(--vcpus ${NUM_CPU})
  VIRT_OPT+=(--ram ${MEM_SIZE})
  VIRT_OPT+=(--disk "pool=${POOL},bus=virtio,format=${STORAGE_FORMAT},sparse=${SPARSE},size=${DISK_SIZE}")
  VIRT_OPT+=(--network network:default,model=virtio)
  VIRT_OPT+=(--os-variant ${OS_VALIANT})
  VIRT_OPT+=(--accelerate)
  VIRT_OPT+=(--nographics)
  VIRT_OPT+=(${INITRD_PARAM})
  VIRT_OPT+=(${INSTALL_FROM})
  ## FIXME この行だけは配列で渡すとインストールが途中で失敗する(CentOS7.3)
  #VIRT_OPT+=("--extra-args='ks=${KS_URL} console=tty0 console=ttyS0,115200n8'")

  # execute virt-install
  if [ ! "$WHY_RUN" ]; then
    echo -e "Everything OK. Start virt-install...\n"

    # execute virt-install
    local START_TIME=`date`
    virt-install "${VIRT_OPT[@]}" \
      --extra-args="ks=$KS_URL console=tty0 console=ttyS0,115200n8"
    local END_TIME=`date`

    echo -e "${C_CYAN}Start time: ${C_OFF}${START_TIME}"
    echo -e "${C_CYAN}End time  : ${C_OFF}${END_TIME}"

    # post install process
    VIRT_STATUS=$?
    if [[ $VIRT_STATUS -eq 0 ]]; then
      echo -e "${C_GREEN}Successfully installed.${C_OFF}"
      echo ''
      echo 'If you want to define /etc/hosts , prease execute folowing command.'
      echo "echo '${IP_ADDR} ${HOST_NAME}' >> /etc/hosts"
    else
      echo -e "${C_RED}Install failed.${C_OFF}"
    fi
  else
    # dry run
    echo -e "${C_YELLOW}[${KS_WORK_FILE} from ${KS_CFG_PATH}]${C_OFF}"
    cat "${KS_WORK_FILE}"
    echo ''
    echo -e "${C_YELLOW}[Why run]${C_OFF}"
    echo "virt-install ${VIRT_OPT[@]} --extra-args=\"ks=$KS_URL console=tty0 console=ttyS0,115200n8\""
  fi
}
#}}}

################################################################################
# install qemu-forward script
################################################################################
_install-qemu-forward() { #{{{
  if [[ ! -f "${QEMU_HOOK}" ]]; then
    local QEMU_DIR=`dirname ${QEMU_HOOK}`
    if [[ ! -d "${QEMU_DIR}" ]]; then
      mkdir -p "${QEMU_DIR}"
      chmod 755 "${QEMU_DIR}"
    fi

    ln -s ${SCRIPT_BASE}/qemu-forward ${QEMU_HOOK}
    if [[ $? -eq 0 ]]; then
      echo -e "${C_GREEN}Successfully installed.${C_OFF}"
      ls -la ${QEMU_HOOK}
    else
      echo -e "${C_RED}Install failed.${C_OFF} ${SCRIPT_BASE}/qemu-forward to ${QEMU_HOOK}"
      exit 1
    fi
  else
    echo -e "${C_YELLOW}${QEMU_HOOK} is already exists.${C_OFF}"
    ls -la ${QEMU_HOOK}
    exit 1
  fi
}
#}}}

__setupcolor

# check command
[[ $# -lt 1 ]] && _usage
case "$1" in
  setup) CMD=$1
    [[ $# -lt 2 ]] && _usage
    KS_PATH="$2"
    shift 2
    ;;
  create) CMD=$1
    [[ $# -lt 2 ]] && _usage
    KS_CFG_PATH="$2"
    shift 2
    ;;
  install-qemu-forward) CMD=$1
    shift 1
    ;;
  *) _usage
    ;;
esac

# Get options
while getopts wh:o:c:m:f:d:i:g:n:p:OH OPT; do
  case "$OPT" in
    w) WHY_RUN=yes ;;
    h) HOST_NAME="$OPTARG" ;;
    o) OS="$OPTARG" ;;
    c) NUM_CPU="$OPTARG" ;;
    m) MEM_SIZE="$OPTARG" ;;
    f) STORAGE_FORMAT_ORG="$OPTARG" ;;
    d) DISK_SIZE="$OPTARG" ;;
    i) IP="$OPTARG" ;;
    g) GATEWAY="$OPTARG" ;;
    n) NAME_SERVER="$OPTARG" ;;
    p) ISO_PATH="$OPTARG" ;;
    O) OFFLINE=yes
       OPTARR=("$@"); ARG=$(echo "${OPTARR[`expr $OPTIND - 1`]}")
       if [[ ! "$ARG" =~ ^-.+ ]]; then
         CMD_ISO_PATH="$ARG"
         shift 1
       fi
       unset OPTARR; unset ARG
      ;;
    \?|H) _usage ;;
  esac
done
shift `expr $OPTIND - 1`

# adjust storage format
_init_storage_format $STORAGE_FORMAT_ORG

# execute command
case "$CMD" in
  setup)  _setup ;;
  create) _create ;;
  install-qemu-forward) _install-qemu-forward ;;
esac

exit 0


# vim: ts=2 sw=2 sts=2 et nu foldmethod=marker
